server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-aa45dghw.bj.tencentcdb.com:10150/amap?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: amap
    password: amap!123

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatisdemo2.dao
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        mybatisdemo2:
          dao: debug